### ISSUE TITLE
Support date ranges (incomplete or slash-delimited)

### ISSUE THREAD

**Issue by corneliusroemer** [fathominfo/delphy-web#34]
In the wild, dates are rarely all known to the exact day (`YYYY-MM-DD`). However this appears to be a strict requirement for Delphy at the moment, limiting usefulness.

It would be great if you could support incomplete dates, there's no fundamental reason why Bayesian inference shouldn't be able to deal with partially knonw/unknown date information.

The most common way incomplete dates are found in the wild is as `YYYY`, `YYYY-MM` or with date entirely missing. This is how Genbank, GISAID etc represent incomplete dates most of the time.

Bonus: A more powerful but till now still rarely used format is the ISO8601 date range syntax where the start and end are separated by slash, e.g. `2023-04-03/2023-05-07`.

**Comment by patvarilly** [comment]
Hi, Cornelius,

We know!  Up to now, we've just been imputing uncertain dates manually to the middle of the date range.  We've been working to relax this restriction over the past two weeks, and we think the changes are ready to go (exactly as you described, including the ISO8601 date range syntax).  They're merged into `main` here, and should go up on [delphy.fathom.info](https://delphy.fathom.info) later today.

One caveat: we've noticed that if many tips have a lot of uncertainty (e.g., `2024` for a good third of all public H5N1 sequences), we start having terrible convergence problems that we thought were behind us with the use of mdSPR moves.  We think that making mdSPR simultaneously adjust tip dates as it migrates tips across the tree should take care of that, but that's not yet implemented.  Stay tuned!
